### ISSUE TITLE
Expose config to jade views.

### ISSUE THREAD

**Issue by tonymilne** [inlight-media/www-foundation#3]
The jade templates currently do not have access to the variables defined in the config.json file.

This `tasks/jade.js` file needs updating, this issue will be addressed when the following line is resolved:

```
    // @TODO: Add config file here.
```

**Comment by oliverbenns** [comment]
This was fixed [here](https://github.com/inlight-media/www-foundation/pull/11), I just retested now and it's working well. Although we still don't currently have anything set up for different environments. I've created a [new issue for this](https://github.com/inlight-media/www-foundation/issues/21).
